/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 faceprofilewire.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/faceprofilewire-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model003.geometry} material={materials['material_0.003']} position={[0.073, 0.724, 0.027]} rotation={[Math.PI / 2, 0, 0]} scale={10} />
    </group>
  )
}

useGLTF.preload('/faceprofilewire-transformed.glb')
