/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 faceprofile.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/faceprofile-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <points geometry={nodes.model003.geometry} material={nodes.model003.material} position={[0.073, 0.724, 0.027]} rotation={[Math.PI / 2, 0, 0]} scale={10}>
        <pointsMaterial size={0.005}></pointsMaterial>
      </points>
    </group>
  )
}

useGLTF.preload('/faceprofile-transformed.glb')
