import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link"
import styles from "./layout.module.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.topLevelHeader}>
          <nav className={styles.topLevelNav}>
            <Link href="/">Home</Link>
            <Link href="/">About</Link>
            <Link href="/testroute">Portfolio</Link>
            <Link href="/">Contact</Link>
          </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
